#define FLT_ROUNDS @\seebelow@
#define FLT_EVAL_METHOD @\seebelow@
#define FLT_HAS_SUBNORM @\seebelow@
#define DBL_HAS_SUBNORM @\seebelow@
#define LDBL_HAS_SUBNORM @\seebelow@
#define FLT_RADIX @\seebelow@
#define FLT_MANT_DIG @\seebelow@
#define DBL_MANT_DIG @\seebelow@
#define LDBL_MANT_DIG @\seebelow@
#define FLT_DECIMAL_DIG @\seebelow@
#define DBL_DECIMAL_DIG @\seebelow@
#define LDBL_DECIMAL_DIG @\seebelow@
#define DECIMAL_DIG @\seebelow@
#define FLT_DIG @\seebelow@
#define DBL_DIG @\seebelow@
#define LDBL_DIG @\seebelow@
#define FLT_MIN_EXP @\seebelow@
#define DBL_MIN_EXP @\seebelow@
#define LDBL_MIN_EXP @\seebelow@
#define FLT_MIN_10_EXP @\seebelow@
#define DBL_MIN_10_EXP @\seebelow@
#define LDBL_MIN_10_EXP @\seebelow@
#define FLT_MAX_EXP @\seebelow@
#define DBL_MAX_EXP @\seebelow@
#define LDBL_MAX_EXP @\seebelow@
#define FLT_MAX_10_EXP @\seebelow@
#define DBL_MAX_10_EXP @\seebelow@
#define LDBL_MAX_10_EXP @\seebelow@
#define FLT_MAX @\seebelow@
#define DBL_MAX @\seebelow@
#define LDBL_MAX @\seebelow@
#define FLT_EPSILON @\seebelow@
#define DBL_EPSILON @\seebelow@
#define LDBL_EPSILON @\seebelow@
#define FLT_MIN @\seebelow@
#define DBL_MIN @\seebelow@
#define LDBL_MIN @\seebelow@
#define FLT_TRUE_MIN @\seebelow@
#define DBL_TRUE_MIN @\seebelow@
#define LDBL_TRUE_MIN @\seebelow@
