#define CHAR_BIT @\seebelow@
#define SCHAR_MIN @\seebelow@
#define SCHAR_MAX @\seebelow@
#define UCHAR_MAX @\seebelow@
#define CHAR_MIN @\seebelow@
#define CHAR_MAX @\seebelow@
#define MB_LEN_MAX @\seebelow@
#define SHRT_MIN @\seebelow@
#define SHRT_MAX @\seebelow@
#define USHRT_MAX @\seebelow@
#define INT_MIN @\seebelow@
#define INT_MAX @\seebelow@
#define UINT_MAX @\seebelow@
#define LONG_MIN @\seebelow@
#define LONG_MAX @\seebelow@
#define ULONG_MAX @\seebelow@
#define LLONG_MIN @\seebelow@
#define LLONG_MAX @\seebelow@
#define ULLONG_MAX @\seebelow@
