#define errno @\seebelow@

#define E2BIG @\seebelow@
#define EACCES @\seebelow@
#define EADDRINUSE @\seebelow@
#define EADDRNOTAVAIL @\seebelow@
#define EAFNOSUPPORT @\seebelow@
#define EAGAIN @\seebelow@
#define EALREADY @\seebelow@
#define EBADF @\seebelow@
#define EBADMSG @\seebelow@
#define EBUSY @\seebelow@
#define ECANCELED @\seebelow@
#define ECHILD @\seebelow@
#define ECONNABORTED @\seebelow@
#define ECONNREFUSED @\seebelow@
#define ECONNRESET @\seebelow@
#define EDEADLK @\seebelow@
#define EDESTADDRREQ @\seebelow@
#define EDOM @\seebelow@
#define EEXIST @\seebelow@
#define EFAULT @\seebelow@
#define EFBIG @\seebelow@
#define EHOSTUNREACH @\seebelow@
#define EIDRM @\seebelow@
#define EILSEQ @\seebelow@
#define EINPROGRESS @\seebelow@
#define EINTR @\seebelow@
#define EINVAL @\seebelow@
#define EIO @\seebelow@
#define EISCONN @\seebelow@
#define EISDIR @\seebelow@
#define ELOOP @\seebelow@
#define EMFILE @\seebelow@
#define EMLINK @\seebelow@
#define EMSGSIZE @\seebelow@
#define ENAMETOOLONG @\seebelow@
#define ENETDOWN @\seebelow@
#define ENETRESET @\seebelow@
#define ENETUNREACH @\seebelow@
#define ENFILE @\seebelow@
#define ENOBUFS @\seebelow@
#define ENODATA @\seebelow@
#define ENODEV @\seebelow@
#define ENOENT @\seebelow@
#define ENOEXEC @\seebelow@
#define ENOLCK @\seebelow@
#define ENOLINK @\seebelow@
#define ENOMEM @\seebelow@
#define ENOMSG @\seebelow@
#define ENOPROTOOPT @\seebelow@
#define ENOSPC @\seebelow@
#define ENOSR @\seebelow@
#define ENOSTR @\seebelow@
#define ENOSYS @\seebelow@
#define ENOTCONN @\seebelow@
#define ENOTDIR @\seebelow@
#define ENOTEMPTY @\seebelow@
#define ENOTRECOVERABLE @\seebelow@
#define ENOTSOCK @\seebelow@
#define ENOTSUP @\seebelow@
#define ENOTTY @\seebelow@
#define ENXIO @\seebelow@
#define EOPNOTSUPP @\seebelow@
#define EOVERFLOW @\seebelow@
#define EOWNERDEAD @\seebelow@
#define EPERM @\seebelow@
#define EPIPE @\seebelow@
#define EPROTO @\seebelow@
#define EPROTONOSUPPORT @\seebelow@
#define EPROTOTYPE @\seebelow@
#define ERANGE @\seebelow@
#define EROFS @\seebelow@
#define ESPIPE @\seebelow@
#define ESRCH @\seebelow@
#define ETIME @\seebelow@
#define ETIMEDOUT @\seebelow@
#define ETXTBSY @\seebelow@
#define EWOULDBLOCK @\seebelow@
#define EXDEV @\seebelow@
